@host = https://localhost:5001

GET {{ host }}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4NGQ0Mzk3NC0zODY4LTQ3ODgtOTBkMy0zOWRhMGU4ZWIwMzMiLCJnaXZlbl9uYW1lIjoiSmFkZSIsImZhbWlseV9uYW1lIjoiRnJlZWwiLCJqdGkiOiJiMzBkNWRjNC0zY2U0LTQzMTQtOGZlZi1iNWM0NThjMjY0MGUiLCJleHAiOjE3NDY0ODI0MDgsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.9ZWQg0ddBjrqdNz5P55Nl5y3vgPdf_Al4pOzKyvFf-Y

###